version: '3'
services:
  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3080:80"
    depends_on:
      - nodeserver
      - client
  nodeserver:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server/
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/:/app
    environment:
      
      - NODE_ENV=production
    ports:
      - "4000:4000"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client/
    volumes:
      - ./client/node_modules:/app/node_modules
      - ./client/:/app
    ports:
      - "3000:3000"



